var retailer = {
	'position': '北京',
	'market_recommend': [{
		'market_name': '水屯批发市场',
		'market_id': '0011'
	}, {
		'market_name': '岳各庄批发市场',
		'market_id': '0012'
	}],
	'banner_list': [],
	'goods_recommend': [{
		'goods_name': '特级白菜',
		'goods_id': '000001',
		'price': '1.99',
		'standard': '10斤/袋',
		'shop_id': '00000',
		'market_id': '0012',
		'url': './images/goods_03.png'
	}, {
		'goods_name': '特级西红柿',
		'goods_id': '000001',
		'price': '1.99',
		'standard': '10斤/袋',
		'shop_id': '00000',
		'market_id': '0012',
		'url': './images/goods_03.png'
	}, {
		'goods_name': '特级肉',
		'goods_id': '000001',
		'price': '1.99',
		'standard': '10斤/袋',
		'shop_id': '00000',
		'market_id': '0012',
		'level': '特A',
		'url': './images/goods_07.png'
	}, {
		'goods_name': '特级黄瓜',
		'goods_id': '000001',
		'price': '1.99',
		'standard': '10斤/袋',
		'shop_id': '00000',
		'market_id': '0012',
		'url': './images/goods_07.png'
	}],
	'nearby': {
		'market_id': '0001',
		'market_name': '水屯批发市场',
		'belong_to': '昌平区水屯批发中心',
		'url': './images/goods_07.png'
	},
	'avata': './images/avata.png',
	'user_name': '志恒达',
	'user_id': '0000000001',
	'token': '472634723647236',
	'identity': '0',
	'order': [{
		'order_code': '123123213000001',
		'shop_id': '123123',
		'shop_name': 'xxxxx店铺名称',
		'state': '待配货',
		'pay_state': '已付款',
		'allPrice': '1000',
		'pay_way': '定期结算',
		'send_way': '到店自取',
		'order_time': '2017-06-19-15:20',
		'remark': '不要辣',
		'goodsList': [{
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}]

	}, {
		'order_code': '12312321000000',
		'shop_id': '123123',
		'shop_name': 'xxxxx店铺名称',
		'state': '已收货',
		'pay_state': '未付款',
		'allPrice': '100220',
		'pay_way': '在线支付',
		'send_way': '到店自取',
		'order_time': '2017-06-19-15:20',
		'remark': '不要辣哈哈哈哈哈',
		'goodsList': [{
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}, {
			'goods_id': '123213',
			'goods_name': '西红柿',
			'price': '12.9',
			'count': '20',
			'standard': '10斤/袋',
			'url': './images/goods_03.png',
			'total_price': '100',
			'url': './images/goods_07.png'
		}]

	}],
	'search_info': {
		'hot': ['黄瓜', '特价黄瓜', '水屯'],
		'hostory': ['黄瓜', '特价黄瓜', '西红柿'],
		'key_word': ['黄瓜', '特价黄瓜', '西红柿', '黄瓜', '特价黄瓜', '西红柿'],
		'result': {
			'have_buy': [{
				'goods_name': '特级白菜1',
				'goods_id': '000001',
				'price': '1.99',
				'standard': '10斤/袋',
				'shop_id': '0000010',
				'shop_name': 'xxxxx店铺名称',
				'market_id': '0012',
				'market_name': '水屯批发市场',
				'url': './images/goods_03.png',
				'count': 1,
				'isChecked': true
			}, {
				'goods_name': '特级白菜2',
				'goods_id': '000002',
				'price': '1.99',
				'standard': '10斤/袋',
				'shop_id': '0000010',
				'shop_name': 'xxxxx店铺名称',
				'market_id': '0012',
				'market_name': '水屯批发市场',
				'url': './images/goods_03.png',
				'count': 1,
				'isChecked': true
			}],
			'first_buy': [{
				'goods_name': '特级白菜3',
				'goods_id': '000003',
				'price': '1.99',
				'standard': '10斤/袋',
				'shop_id': '0000011',
				'shop_name': 'xxxxx店铺名称',
				'market_id': '0012',
				'market_name': '水屯批发市场',
				'url': './images/goods_03.png',
				'count': 1,
				'isChecked': true
			}, {
				'goods_name': '特级白菜4',
				'goods_id': '000004',
				'price': '1.99',
				'standard': '10斤/袋',
				'shop_id': '0000011',
				'shop_name': 'xxxxx店铺名称',
				'market_id': '0012',
				'market_name': '水屯批发市场',
				'url': './images/goods_03.png',
				'count': 1,
				'isChecked': true
			}, {
				'goods_name': '特级白菜5',
				'goods_id': '000005',
				'price': '1.99',
				'standard': '10斤/袋',
				'shop_id': '0000012',
				'shop_name': 'xxxxx店铺名称',
				'market_id': '0012',
				'market_name': '水屯批发市场',
				'url': './images/goods_03.png',
				'count': 1,
				'isChecked': true
			}, {
				'goods_name': '特级白菜6',
				'goods_id': '000006',
				'price': '1.99',
				'standard': '10斤/袋',
				'shop_id': '0000012',
				'shop_name': 'xxxxx店铺名称',
				'market_id': '0012',
				'market_name': '水屯批发市场',
				'url': './images/goods_03.png',
				'count': 1,
				'isChecked': true
			}]
		}
	}


}
module.exports.retailer = retailer;